//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

#import <AVKit/AVKit.h>
#import <GLKit/GLKit.h>
#import <NSFoundation/NSFoundation.h>
#import <Rswift/Rswift.h>
#import <SWRevealViewController/SWRevealViewController.h>
#import <UIKit/UIKit.h>

/// This `.storyboard` struct is generated, and contains static references to 4 storyboards.
@implementation UIStoryboardasdf (storyboardasdf)   
/// `UIStoryboard(name: "Main", bundle: ...)`
 
+ (UIStoryboardasdf *)main_:(voidbbbb *)_ {
     return UIKit.UIStoryboard(resource: R.storyboard.main)
}

/// `UIStoryboard(name: "References", bundle: ...)`
 
+ (UIStoryboardasdf *)references_:(voidbbbb *)_ {
     return UIKit.UIStoryboard(resource: R.storyboard.references)
}

/// `UIStoryboard(name: "Secondary", bundle: ...)`
 
+ (UIStoryboardasdf *)secondary_:(voidbbbb *)_ {
     return UIKit.UIStoryboard(resource: R.storyboard.secondary)
}

/// `UIStoryboard(name: "Specials", bundle: ...)`
 
+ (UIStoryboardasdf *)specials_:(voidbbbb *)_ {
     return UIKit.UIStoryboard(resource: R.storyboard.specials)
}
@end


