//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

#import <AVKit/AVKit.h>
#import <GLKit/GLKit.h>
#import <NSFoundation/NSFoundation.h>
#import <Rswift/Rswift.h>
#import <SWRevealViewController/SWRevealViewController.h>
#import <UIKit/UIKit.h>

/// This `.storyboard` struct is generated, and contains static references to 4 storyboards.
@implementation UIStoryboarda (storyboarda)   
/// `UIStoryboard(name: "Main", bundle: ...)`
 
+ (UIStoryboarda *)main_:(void *)_ {
     return UIKit.UIStoryboard(resource: R.storyboard.main)
}

/// `UIStoryboard(name: "References", bundle: ...)`
 
+ (UIStoryboarda *)references_:(void *)_ {
     return UIKit.UIStoryboard(resource: R.storyboard.references)
}

/// `UIStoryboard(name: "Secondary", bundle: ...)`
 
+ (UIStoryboarda *)secondary_:(void *)_ {
     return UIKit.UIStoryboard(resource: R.storyboard.secondary)
}

/// `UIStoryboard(name: "Specials", bundle: ...)`
 
+ (UIStoryboarda *)specials_:(void *)_ {
     return UIKit.UIStoryboard(resource: R.storyboard.specials)
}
@end


