//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

#import <AVKit/AVKit.h>
#import <GLKit/GLKit.h>
#import <NSFoundation/NSFoundation.h>
#import <Rswift/Rswift.h>
#import <SWRevealViewController/SWRevealViewController.h>
#import <UIKit/UIKit.h>

/// This `.storyboard` struct is generated, and contains static references to 4 storyboards.

@interface UIStoryboard * (storyboard *)  
/// `UIStoryboard(name: "Main", bundle: ...)`
 
+ (UIStoryboard * *)main_:(void *)_;

/// `UIStoryboard(name: "References", bundle: ...)`
 
+ (UIStoryboard * *)references_:(void *)_;

/// `UIStoryboard(name: "Secondary", bundle: ...)`
 
+ (UIStoryboard * *)secondary_:(void *)_;

/// `UIStoryboard(name: "Specials", bundle: ...)`
 
+ (UIStoryboard * *)specials_:(void *)_;
@end


