//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

#import <Rswift/Rswift.h>
#import <SWRevealViewController/SWRevealViewController.h>

/// This `.string` struct is generated, and contains static references to 3 localization tables.
@implementation NSObject (stringasdf)   

@end

/// This `.string.generic` struct is generated, and contains static references to 13 localization keys.
@implementation NSStringasdf (genericasdf)   
/// Value: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
 
+ (NSStringasdf *)loremipsum_:(voidbbbb *)_ {
     return NSLocalizedString("loremipsum", tableName: "Generic", bundle: R.hostingBundle, comment: "")
}

/// Value: Pre Alpha (| %#@first@ |)
 
+ (NSStringasdf *)correctAlphafirstvalue1:(intbbbb *)firstvalue1 {
     return String(format: NSLocalizedString("correct alpha", tableName: "Generic", bundle: R.hostingBundle, comment: ""), locale: R.applicationLocale, value1)
}

/// Value: Pre Beta (| %#@first@ x %#@second@ |)
 
+ (NSStringasdf *)correctBetafirstvalue1:(intbbbb *)firstvalue1 secondvalue2:(intbbbb *)secondvalue2 {
     return String(format: NSLocalizedString("correct beta", tableName: "Generic", bundle: R.hostingBundle, comment: ""), locale: R.applicationLocale, value1, value2)
}

/// Value: Pre Delta (| %#@first@ |)
 
+ (NSStringasdf *)correctDeltafirstvalue1:(intbbbb *)firstvalue1 secondvalue2:(intbbbb *)secondvalue2 {
     return String(format: NSLocalizedString("correct delta", tableName: "Generic", bundle: R.hostingBundle, comment: ""), locale: R.applicationLocale, value1, value2)
}

/// Value: Pre Epsilon (| %#@first@ |)
 
+ (NSStringasdf *)correctEpsilonfirstvalue1:(intbbbb *)firstvalue1 secondvalue2:(intbbbb *)secondvalue2 {
     return String(format: NSLocalizedString("correct epsilon", tableName: "Generic", bundle: R.hostingBundle, comment: ""), locale: R.applicationLocale, value1, value2)
}

/// Value: Pre Eta (| %@ - %#@second@ - %d|)
 
+ (NSStringasdf *)correctEta_value1:(NSStringasdf *)_value1 secondvalue2:(intbbbb *)secondvalue2 _value3:(intbbbb *)_value3 {
     return String(format: NSLocalizedString("correct eta", tableName: "Generic", bundle: R.hostingBundle, comment: ""), locale: R.applicationLocale, value1, value2, value3)
}

/// Value: Pre Gamma (| %2$#@second@ x %1$#@first@ |)
 
+ (NSStringasdf *)correctGammafirstvalue1:(intbbbb *)firstvalue1 secondvalue2:(intbbbb *)secondvalue2 {
     return String(format: NSLocalizedString("correct gamma", tableName: "Generic", bundle: R.hostingBundle, comment: ""), locale: R.applicationLocale, value1, value2)
}

/// Value: Pre Theta (| %#@first@ |)
 
+ (NSStringasdf *)correctThetafirstvalue1:(intbbbb *)firstvalue1 secondvalue2:(intbbbb *)secondvalue2 thirdvalue3:(intbbbb *)thirdvalue3 {
     return String(format: NSLocalizedString("correct theta", tableName: "Generic", bundle: R.hostingBundle, comment: ""), locale: R.applicationLocale, value1, value2, value3)
}

/// Value: Pre Zeta (| %@ %2$#@second@ |)
 
+ (NSStringasdf *)correctZeta_value1:(NSStringasdf *)_value1 secondvalue2:(intbbbb *)secondvalue2 {
     return String(format: NSLocalizedString("correct zeta", tableName: "Generic", bundle: R.hostingBundle, comment: ""), locale: R.applicationLocale, value1, value2)
}

/// Value: four  - %.2f
 
+ (NSStringasdf *)precision4_value1:(doublebbbb *)_value1 {
     return String(format: NSLocalizedString("precision4", tableName: "Generic", bundle: R.hostingBundle, comment: ""), locale: R.applicationLocale, value1)
}

/// Value: one   - %012.2f
 
+ (NSStringasdf *)precision1_value1:(doublebbbb *)_value1 {
     return String(format: NSLocalizedString("precision1", tableName: "Generic", bundle: R.hostingBundle, comment: ""), locale: R.applicationLocale, value1)
}

/// Value: three - %12.4f
 
+ (NSStringasdf *)precision3_value1:(doublebbbb *)_value1 {
     return String(format: NSLocalizedString("precision3", tableName: "Generic", bundle: R.hostingBundle, comment: ""), locale: R.applicationLocale, value1)
}

/// Value: two   - %12.2f
 
+ (NSStringasdf *)precision2_value1:(doublebbbb *)_value1 {
     return String(format: NSLocalizedString("precision2", tableName: "Generic", bundle: R.hostingBundle, comment: ""), locale: R.applicationLocale, value1)
}
@end



/// This `.string.localizable` struct is generated, and contains static references to 4 localization keys.
@implementation NSStringasdf (localizableasdf)   
/// en translation: 2
/// 
/// Locales: en, es, ja
 
+ (NSStringasdf *)two_:(voidbbbb *)_ {
     return NSLocalizedString("two", bundle: R.hostingBundle, comment: "")
}

/// en translation: One
/// 
/// Locales: en, es, ja
 
+ (NSStringasdf *)one_:(voidbbbb *)_ {
     return NSLocalizedString("one", bundle: R.hostingBundle, comment: "")
}

/// en translation: There are %d lights!
/// 
/// Locales: en, es, ja
 
+ (NSStringasdf *)quote_value1:(intbbbb *)_value1 {
     return String(format: NSLocalizedString("quote", bundle: R.hostingBundle, comment: ""), locale: R.applicationLocale, value1)
}

/// ja translation: Not translated in other languages, and there is no Base
/// 
/// Locales: ja
 
+ (NSStringasdf *)japaneseOnly_:(voidbbbb *)_ {
     return NSLocalizedString("japanese only", bundle: R.hostingBundle, comment: "")
}
@end



/// This `.string.settings` struct is generated, and contains static references to 10 localization keys.
@implementation NSStringasdf (settingsasdf)   
/// Base translation: %1$#@lu_completed_runs@
/// 
/// Locales: Base, nl
 
+ (NSStringasdf *)scopeLuOutOfLuRunslu_completed_runsvalue1:(uintbbbb *)lu_completed_runsvalue1 lu_total_runsvalue2:(uintbbbb *)lu_total_runsvalue2 {
     return String(format: NSLocalizedString("scope.%lu out of %lu runs", tableName: "Settings", bundle: R.hostingBundle, value: "%1$#@lu_completed_runs@", comment: ""), locale: R.applicationLocale, value1, value2)
}

/// Base translation: %1$d of %2$i files copied, %3$f.2%% completed.
/// 
/// Locales: Base, nl
 
+ (NSStringasdf *)copyProgress_value1:(intbbbb *)_value1 _value2:(intbbbb *)_value2 _value3:(doublebbbb *)_value3 {
     return String(format: NSLocalizedString("Copy.Progress", tableName: "Settings", bundle: R.hostingBundle, value: "%1$d of %2$i files copied, %3$f.2%% completed.", comment: ""), locale: R.applicationLocale, value1, value2, value3)
}

/// Base translation: ABC "\DEF/" GHI Base
/// 
/// Locales: Base, nl
 
+ (NSStringasdf *)multilineKeyWeird_:(voidbbbb *)_ {
     return NSLocalizedString("Multiline\t\\key/\n\"weird\"?!", tableName: "Settings", bundle: R.hostingBundle, value: "ABC\n\"\\DEF/\"\nGHI Base", comment: "")
}

/// Base translation: Base %#@first@
/// 
/// Locales: Base
 
+ (NSStringasdf *)incorrectInDutchfirstvalue1:(intbbbb *)firstvalue1 {
     return String(format: NSLocalizedString("incorrect in dutch", tableName: "Settings", bundle: R.hostingBundle, value: "Base %#@first@", comment: ""), locale: R.applicationLocale, value1)
}

/// Base translation: Base language; Not translated
/// 
/// Locales: Base
 
+ (NSStringasdf *)notTranslated_:(voidbbbb *)_ {
     return NSLocalizedString("Not translated", tableName: "Settings", bundle: R.hostingBundle, value: "Base language; Not translated", comment: "")
}

/// Base translation: Nothing
/// 
/// Locales: Base, nl
 
+ (NSStringasdf *)formatSpecifiers3_value1:(intbbbb *)_value1 _value2:(intbbbb *)_value2 _value3:(NSStringasdf *)_value3 {
     return String(format: NSLocalizedString("FormatSpecifiers3", tableName: "Settings", bundle: R.hostingBundle, value: "Nothing", comment: ""), locale: R.applicationLocale, value1, value2, value3)
}

/// Base translation: Settings
/// 
/// Locales: Base, nl
 
+ (NSStringasdf *)title_:(voidbbbb *)_ {
     return NSLocalizedString("Title", tableName: "Settings", bundle: R.hostingBundle, value: "Settings", comment: "")
}

/// Base translation: We need a couple things before you get started.
/// 
/// Locales: Base, nl
 
+ (NSStringasdf *)weNeedACoupleThingsBeforeYouGetStarted_:(voidbbbb *)_ {
     return NSLocalizedString("We need a couple things\r\nbefore you get started.", tableName: "Settings", bundle: R.hostingBundle, value: "We need a couple things\r\nbefore you get started.", comment: "")
}

/// Base translation: number 1: %1$d
/// 
/// Locales: Base, nl
 
+ (NSStringasdf *)formatSpecifiers4_value1:(intbbbb *)_value1 _value2:(intbbbb *)_value2 _value3:(NSStringasdf *)_value3 {
     return String(format: NSLocalizedString("FormatSpecifiers4", tableName: "Settings", bundle: R.hostingBundle, value: "number 1: %1$d", comment: ""), locale: R.applicationLocale, value1, value2, value3)
}

/// Base translation: number 1: %d, number 2: %i, string 3: %@
/// 
/// Locales: Base, nl
 
+ (NSStringasdf *)formatSpecifiers1_value1:(intbbbb *)_value1 _value2:(intbbbb *)_value2 _value3:(NSStringasdf *)_value3 {
     return String(format: NSLocalizedString("FormatSpecifiers1", tableName: "Settings", bundle: R.hostingBundle, value: "number 1: %d, number 2: %i, string 3: %@", comment: ""), locale: R.applicationLocale, value1, value2, value3)
}
@end


