//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

#import "FirstViewController.h"
#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

/// NSObject no func and structs

/// This R`R.image.namespace.inner.namespace` struct is generated, and contains static references to 1 images.

@interface UIImage (R_image_namespace_inner_namespace) 

/// return [[UIImage imageNamed:@"first"] imageWithRenderingMode:renderingMode];
+ (UIImage *)firstRenderingMode:(UIImageRenderingMode)renderingMode;

/// return [[UIImage imageNamed:@"first"] imageWithRenderingMode:renderingMode];
+ (UIImage *)first;
@end



/// This R`R.nib` struct is generated, and contains static references to 10 nibs.

@interface UINib (NibExternal) 

/// `[UINib nibWithNibName:@"ADuplicateCellView" bundle:nil]`
+ (UINib *)aDuplicateCellView;


/// `[UINib nibWithNibName:@"CellCollectionView" bundle:nil]`
+ (UINib *)cellCollectionView;


/// `[UINib nibWithNibName:@"CellView" bundle:nil]`
+ (UINib *)cellView;


/// `[UINib nibWithNibName:@"DuplicateCellView" bundle:nil]`
+ (UINib *)duplicateCellView;


/// `[UINib nibWithNibName:@"LaunchScreen" bundle:nil]`
+ (UINib *)launchScreen;


/// `[UINib nibWithNibName:@"My View" bundle:nil]`
+ (UINib *)myView;


/// `[UINib nibWithNibName:@"RelativeToProject" bundle:nil]`
+ (UINib *)relativeToProject;


/// `[UINib nibWithNibName:@"SupplementaryElement" bundle:nil]`
+ (UINib *)supplementaryElement;


/// `[UINib nibWithNibName:@"WhitespaceReuseIdentifer" bundle:nil]`
+ (UINib *)whitespaceReuseIdentifer;


/// `[UINib nibWithNibName:@"Xib with ViewController" bundle:nil]`
+ (UINib *)xibWithViewController;
@end



/// This `R.color.myRSwiftColors` struct is generated, and contains static references to 5 colors.

@interface UIColor (MyRSwiftColors) 

/// <span style='background-color: #6A6A6A4C; color: #959595; padding: 1px 3px;'>#6A6A6A4C</span> See-through gray
/// 
/// [UIColor colorWithRed:0.41758814454078674 green:0.41758814454078674 blue:0.41758814454078674 alpha:0.2982758581638336];
+ (UIColor *)seeThroughGray;


/// <span style='background-color: #B6FFAB; color: #490054; padding: 1px 3px;'>#B6FFAB</span> All is A-OK
/// 
/// [UIColor colorWithRed:0.7140880823135376 green:1.0 blue:0.6687110066413879 alpha:1.0];
+ (UIColor *)allIsAOK;


/// <span style='background-color: #FF8A7E; color: #007581; padding: 1px 3px;'>#FF8A7E</span> Severe error
/// 
/// [UIColor colorWithRed:1.0 green:0.542837381362915 blue:0.4926460087299347 alpha:1.0];
+ (UIColor *)severeError;


/// <span style='background-color: #FFEBA2; color: #00145D; padding: 1px 3px;'>#FFEBA2</span> Warning
/// 
/// [UIColor colorWithRed:1.0 green:0.9210211634635925 blue:0.6361839175224304 alpha:1.0];
+ (UIColor *)warning;


/// <span style='background-color: #FFFCF9; color: #000306; padding: 1px 3px;'>#FFFCF9</span> Slightly off-white
/// 
/// [UIColor colorWithRed:1.0 green:0.9882352948188782 blue:0.9764705896377563 alpha:1.0];
+ (UIColor *)slightlyOffWhite;
@end



/// This `R.font` struct is generated, and contains static references to 5 fonts.

@interface UIFont (Font) 

/// `UIFont(name: "AveriaLibre-Bold", size: ...)`
+ (UIFont *)averiaLibreBoldSize:(CGFloat)size;


/// `UIFont(name: "AveriaLibre-BoldItalic", size: ...)`
+ (UIFont *)averiaLibreBoldItalicSize:(CGFloat)size;


/// `UIFont(name: "AveriaLibre-Light", size: ...)`
+ (UIFont *)averiaLibreLightSize:(CGFloat)size;


/// `UIFont(name: "AveriaLibre-Regular", size: ...)`
+ (UIFont *)averiaLibreRegularSize:(CGFloat)size;


/// `UIFont(name: "GoudyBookletter1911", size: ...)`
+ (UIFont *)goudyBookletter1911Size:(CGFloat)size;
@end



/// This `R.string.generic` struct is generated, and contains static references to 13 localization keys.

@interface NSString (Generic) 

/// Value: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
+ (NSString *)loremipsum;


/// Value: Pre Alpha (| %#@first@ |)
+ (NSString *)correctAlphaFirst:(int)value1;


/// Value: Pre Beta (| %#@first@ x %#@second@ |)
+ (NSString *)correctBetaFirst:(int)value1 Second:(int)value2;


/// Value: Pre Delta (| %#@first@ |)
+ (NSString *)correctDeltaFirst:(int)value1 Second:(int)value2;


/// Value: Pre Epsilon (| %#@first@ |)
+ (NSString *)correctEpsilonFirst:(int)value1 Second:(int)value2;


/// Value: Pre Eta (| %@ - %#@second@ - %d|)
+ (NSString *)correctEtaValue1:(NSString *)value1 Second:(int)value2 Value3:(int)value3;


/// Value: Pre Gamma (| %2$#@second@ x %1$#@first@ |)
+ (NSString *)correctGammaFirst:(int)value1 Second:(int)value2;


/// Value: Pre Theta (| %#@first@ |)
+ (NSString *)correctThetaFirst:(int)value1 Second:(int)value2 Third:(int)value3;


/// Value: Pre Zeta (| %@ %2$#@second@ |)
+ (NSString *)correctZetaValue1:(NSString *)value1 Second:(int)value2;


/// Value: four  - %.2f
+ (NSString *)precision4Value1:(double)value1;


/// Value: one   - %012.2f
+ (NSString *)precision1Value1:(double)value1;


/// Value: three - %12.4f
+ (NSString *)precision3Value1:(double)value1;


/// Value: two   - %12.2f
+ (NSString *)precision2Value1:(double)value1;
@end



/// This `R.string.localizable` struct is generated, and contains static references to 4 localization keys.

@interface NSString (Localizable) 

/// en translation: 2
/// 
/// Locales: en, es, ja
+ (NSString *)two;


/// en translation: One
/// 
/// Locales: en, es, ja
+ (NSString *)one;


/// en translation: There are %d lights!
/// 
/// Locales: en, es, ja
+ (NSString *)quoteValue1:(int)value1;


/// ja translation: Not translated in other languages, and there is no Base
/// 
/// Locales: ja
+ (NSString *)japaneseOnly;
@end



/// This `R.string.settings` struct is generated, and contains static references to 10 localization keys.

@interface NSString (Settings) 

/// Base translation: %1$#@lu_completed_runs@
/// 
/// Locales: Base, nl
+ (NSString *)scopeLuOutOfLuRunsLu_completed_runs:(uint)value1 Lu_total_runs:(uint)value2;


/// Base translation: %1$d of %2$i files copied, %3$f.2%% completed.
/// 
/// Locales: Base, nl
+ (NSString *)copyProgressValue1:(int)value1 Value2:(int)value2 Value3:(double)value3;


/// Base translation: ABC "\DEF/" GHI Base
/// 
/// Locales: Base, nl
+ (NSString *)multilineKeyWeird;


/// Base translation: Base %#@first@
/// 
/// Locales: Base
+ (NSString *)incorrectInDutchFirst:(int)value1;


/// Base translation: Base language; Not translated
/// 
/// Locales: Base
+ (NSString *)notTranslated;


/// Base translation: Nothing
/// 
/// Locales: Base, nl
+ (NSString *)formatSpecifiers3Value1:(int)value1 Value2:(int)value2 Value3:(NSString *)value3;


/// Base translation: Settings
/// 
/// Locales: Base, nl
+ (NSString *)title;


/// Base translation: We need a couple things before you get started.
/// 
/// Locales: Base, nl
+ (NSString *)weNeedACoupleThingsBeforeYouGetStarted;


/// Base translation: number 1: %1$d
/// 
/// Locales: Base, nl
+ (NSString *)formatSpecifiers4Value1:(int)value1 Value2:(int)value2 Value3:(NSString *)value3;


/// Base translation: number 1: %d, number 2: %i, string 3: %@
/// 
/// Locales: Base, nl
+ (NSString *)formatSpecifiers1Value1:(int)value1 Value2:(int)value2 Value3:(NSString *)value3;
@end




@interface UINib (_ADuplicateCellView) 

+ (UITableViewCell *)firstViewOwnerOrNil:(id)ownerOrNil OptionsOrNil:(NSDictionary *)optionsOrNil;

+ (UITableViewCell *)firstViewOwnerOrNil:(id)ownerOrNil;

+ (UITableViewCell *)firstViewOptionsOrNil:(NSDictionary *)optionsOrNil;
@end




@interface UINib (_CellCollectionView) 

+ (UICollectionViewCell *)firstViewOptionsOrNil:(NSDictionary *)optionsOrNil;

+ (UICollectionViewCell *)firstViewOwnerOrNil:(id)ownerOrNil OptionsOrNil:(NSDictionary *)optionsOrNil;

+ (UICollectionViewCell *)firstViewOwnerOrNil:(id)ownerOrNil;
@end




@interface UINib (_CellView) 

+ (UITableViewCell *)firstViewOptionsOrNil:(NSDictionary *)optionsOrNil;

+ (UITableViewCell *)firstViewOwnerOrNil:(id)ownerOrNil;

+ (UITableViewCell *)firstViewOwnerOrNil:(id)ownerOrNil OptionsOrNil:(NSDictionary *)optionsOrNil;
@end




@interface UINib (_DuplicateCellView) 

+ (UITableViewCell *)firstViewOwnerOrNil:(id)ownerOrNil;

+ (UITableViewCell *)firstViewOwnerOrNil:(id)ownerOrNil OptionsOrNil:(NSDictionary *)optionsOrNil;

+ (UITableViewCell *)firstViewOptionsOrNil:(NSDictionary *)optionsOrNil;
@end




@interface UINib (_LaunchScreen) 

+ (UIView *)firstViewOwnerOrNil:(id)ownerOrNil OptionsOrNil:(NSDictionary *)optionsOrNil;

+ (UIView *)firstViewOptionsOrNil:(NSDictionary *)optionsOrNil;

+ (UIView *)firstViewOwnerOrNil:(id)ownerOrNil;
@end




@interface UINib (_MyView) 

+ (UIView *)firstViewOptionsOrNil:(NSDictionary *)optionsOrNil;

+ (UIView *)firstViewOwnerOrNil:(id)ownerOrNil;

+ (UIView *)firstViewOwnerOrNil:(id)ownerOrNil OptionsOrNil:(NSDictionary *)optionsOrNil;
@end




@interface UINib (_RelativeToProject) 

+ (UIView *)firstViewOptionsOrNil:(NSDictionary *)optionsOrNil;

+ (UIView *)firstViewOwnerOrNil:(id)ownerOrNil OptionsOrNil:(NSDictionary *)optionsOrNil;

+ (UIView *)firstViewOwnerOrNil:(id)ownerOrNil;
@end




@interface UINib (_SupplementaryElement) 

+ (UICollectionReusableView *)firstViewOwnerOrNil:(id)ownerOrNil;

+ (UICollectionReusableView *)firstViewOptionsOrNil:(NSDictionary *)optionsOrNil;

+ (UICollectionReusableView *)firstViewOwnerOrNil:(id)ownerOrNil OptionsOrNil:(NSDictionary *)optionsOrNil;
@end




@interface UINib (_WhitespaceReuseIdentifer) 

+ (UITableViewCell *)firstViewOwnerOrNil:(id)ownerOrNil;

+ (UITableViewCell *)firstViewOwnerOrNil:(id)ownerOrNil OptionsOrNil:(NSDictionary *)optionsOrNil;

+ (UITableViewCell *)firstViewOptionsOrNil:(NSDictionary *)optionsOrNil;
@end




@interface UINib (_XibWithViewController) 

+ (FirstViewController *)firstViewOwnerOrNil:(id)ownerOrNil OptionsOrNil:(NSDictionary *)optionsOrNil;

+ (FirstViewController *)firstViewOptionsOrNil:(NSDictionary *)optionsOrNil;

+ (FirstViewController *)firstViewOwnerOrNil:(id)ownerOrNil;


+ (UIView *)secondViewOwnerOrNil:(id)ownerOrNil;

+ (UIView *)secondViewOptionsOrNil:(NSDictionary *)optionsOrNil;

+ (UIView *)secondViewOwnerOrNil:(id)ownerOrNil OptionsOrNil:(NSDictionary *)optionsOrNil;
@end


