//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

#import "R_External.h"

/// This R`.nib` struct is generated, and contains static references to 10 nibs.
@implementation UINib (External) 

/// `[UINib nibWithNibName:@"ADuplicateCellView" bundle:nil]`
+ (UINib *)aDuplicateCellView {
     return [UINib nibWithNibName:@"ADuplicateCellView" bundle:nil];
}


/// `[UINib nibWithNibName:@"CellCollectionView" bundle:nil]`
+ (UINib *)cellCollectionView {
     return [UINib nibWithNibName:@"CellCollectionView" bundle:nil];
}


/// `[UINib nibWithNibName:@"CellView" bundle:nil]`
+ (UINib *)cellView {
     return [UINib nibWithNibName:@"CellView" bundle:nil];
}


/// `[UINib nibWithNibName:@"DuplicateCellView" bundle:nil]`
+ (UINib *)duplicateCellView {
     return [UINib nibWithNibName:@"DuplicateCellView" bundle:nil];
}


/// `[UINib nibWithNibName:@"LaunchScreen" bundle:nil]`
+ (UINib *)launchScreen {
     return [UINib nibWithNibName:@"LaunchScreen" bundle:nil];
}


/// `[UINib nibWithNibName:@"My View" bundle:nil]`
+ (UINib *)myView {
     return [UINib nibWithNibName:@"My View" bundle:nil];
}


/// `[UINib nibWithNibName:@"RelativeToProject" bundle:nil]`
+ (UINib *)relativeToProject {
     return [UINib nibWithNibName:@"RelativeToProject" bundle:nil];
}


/// `[UINib nibWithNibName:@"SupplementaryElement" bundle:nil]`
+ (UINib *)supplementaryElement {
     return [UINib nibWithNibName:@"SupplementaryElement" bundle:nil];
}


/// `[UINib nibWithNibName:@"WhitespaceReuseIdentifer" bundle:nil]`
+ (UINib *)whitespaceReuseIdentifer {
     return [UINib nibWithNibName:@"WhitespaceReuseIdentifer" bundle:nil];
}


/// `[UINib nibWithNibName:@"Xib with ViewController" bundle:nil]`
+ (UINib *)xibWithViewController {
     return [UINib nibWithNibName:@"Xib with ViewController" bundle:nil];
}
@end



@implementation UINib (_ADuplicateCellView) 

+ (UITableViewCell *)firstViewOwnerOrNil:(id)ownerOrNil {
     return [[UINib alloc] instantiateWithOwner:ownerOrNil options:nil][0];
}

+ (UITableViewCell *)firstViewOptionsOrNil:(NSDictionary *)optionsOrNil {
     return [[UINib alloc] instantiateWithOwner:nil options:optionsOrNil][0];
}

+ (UITableViewCell *)firstViewOwnerOrNil:(id)ownerOrNil OptionsOrNil:(NSDictionary *)optionsOrNil {
     return [[UINib alloc] instantiateWithOwner:ownerOrNil options:optionsOrNil][0];
}
@end



@implementation UINib (_CellCollectionView) 

+ (UICollectionViewCell *)firstViewOwnerOrNil:(id)ownerOrNil OptionsOrNil:(NSDictionary *)optionsOrNil {
     return [[UINib alloc] instantiateWithOwner:ownerOrNil options:optionsOrNil][0];
}

+ (UICollectionViewCell *)firstViewOptionsOrNil:(NSDictionary *)optionsOrNil {
     return [[UINib alloc] instantiateWithOwner:nil options:optionsOrNil][0];
}

+ (UICollectionViewCell *)firstViewOwnerOrNil:(id)ownerOrNil {
     return [[UINib alloc] instantiateWithOwner:ownerOrNil options:nil][0];
}
@end



@implementation UINib (_CellView) 

+ (UITableViewCell *)firstViewOwnerOrNil:(id)ownerOrNil {
     return [[UINib alloc] instantiateWithOwner:ownerOrNil options:nil][0];
}

+ (UITableViewCell *)firstViewOptionsOrNil:(NSDictionary *)optionsOrNil {
     return [[UINib alloc] instantiateWithOwner:nil options:optionsOrNil][0];
}

+ (UITableViewCell *)firstViewOwnerOrNil:(id)ownerOrNil OptionsOrNil:(NSDictionary *)optionsOrNil {
     return [[UINib alloc] instantiateWithOwner:ownerOrNil options:optionsOrNil][0];
}
@end



@implementation UINib (_DuplicateCellView) 

+ (UITableViewCell *)firstViewOwnerOrNil:(id)ownerOrNil {
     return [[UINib alloc] instantiateWithOwner:ownerOrNil options:nil][0];
}

+ (UITableViewCell *)firstViewOptionsOrNil:(NSDictionary *)optionsOrNil {
     return [[UINib alloc] instantiateWithOwner:nil options:optionsOrNil][0];
}

+ (UITableViewCell *)firstViewOwnerOrNil:(id)ownerOrNil OptionsOrNil:(NSDictionary *)optionsOrNil {
     return [[UINib alloc] instantiateWithOwner:ownerOrNil options:optionsOrNil][0];
}
@end



@implementation UINib (_LaunchScreen) 

+ (UIView *)firstViewOwnerOrNil:(id)ownerOrNil OptionsOrNil:(NSDictionary *)optionsOrNil {
     return [[UINib alloc] instantiateWithOwner:ownerOrNil options:optionsOrNil][0];
}

+ (UIView *)firstViewOwnerOrNil:(id)ownerOrNil {
     return [[UINib alloc] instantiateWithOwner:ownerOrNil options:nil][0];
}

+ (UIView *)firstViewOptionsOrNil:(NSDictionary *)optionsOrNil {
     return [[UINib alloc] instantiateWithOwner:nil options:optionsOrNil][0];
}
@end



@implementation UINib (_MyView) 

+ (UIView *)firstViewOwnerOrNil:(id)ownerOrNil OptionsOrNil:(NSDictionary *)optionsOrNil {
     return [[UINib alloc] instantiateWithOwner:ownerOrNil options:optionsOrNil][0];
}

+ (UIView *)firstViewOwnerOrNil:(id)ownerOrNil {
     return [[UINib alloc] instantiateWithOwner:ownerOrNil options:nil][0];
}

+ (UIView *)firstViewOptionsOrNil:(NSDictionary *)optionsOrNil {
     return [[UINib alloc] instantiateWithOwner:nil options:optionsOrNil][0];
}
@end



@implementation UINib (_RelativeToProject) 

+ (UIView *)firstViewOwnerOrNil:(id)ownerOrNil OptionsOrNil:(NSDictionary *)optionsOrNil {
     return [[UINib alloc] instantiateWithOwner:ownerOrNil options:optionsOrNil][0];
}

+ (UIView *)firstViewOwnerOrNil:(id)ownerOrNil {
     return [[UINib alloc] instantiateWithOwner:ownerOrNil options:nil][0];
}

+ (UIView *)firstViewOptionsOrNil:(NSDictionary *)optionsOrNil {
     return [[UINib alloc] instantiateWithOwner:nil options:optionsOrNil][0];
}
@end



@implementation UINib (_SupplementaryElement) 

+ (UICollectionReusableView *)firstViewOwnerOrNil:(id)ownerOrNil {
     return [[UINib alloc] instantiateWithOwner:ownerOrNil options:nil][0];
}

+ (UICollectionReusableView *)firstViewOptionsOrNil:(NSDictionary *)optionsOrNil {
     return [[UINib alloc] instantiateWithOwner:nil options:optionsOrNil][0];
}

+ (UICollectionReusableView *)firstViewOwnerOrNil:(id)ownerOrNil OptionsOrNil:(NSDictionary *)optionsOrNil {
     return [[UINib alloc] instantiateWithOwner:ownerOrNil options:optionsOrNil][0];
}
@end



@implementation UINib (_WhitespaceReuseIdentifer) 

+ (UITableViewCell *)firstViewOwnerOrNil:(id)ownerOrNil {
     return [[UINib alloc] instantiateWithOwner:ownerOrNil options:nil][0];
}

+ (UITableViewCell *)firstViewOptionsOrNil:(NSDictionary *)optionsOrNil {
     return [[UINib alloc] instantiateWithOwner:nil options:optionsOrNil][0];
}

+ (UITableViewCell *)firstViewOwnerOrNil:(id)ownerOrNil OptionsOrNil:(NSDictionary *)optionsOrNil {
     return [[UINib alloc] instantiateWithOwner:ownerOrNil options:optionsOrNil][0];
}
@end



@implementation UINib (_XibWithViewController) 

+ (FirstViewController *)firstViewOwnerOrNil:(id)ownerOrNil {
     return [[UINib alloc] instantiateWithOwner:ownerOrNil options:nil][0];
}

+ (FirstViewController *)firstViewOwnerOrNil:(id)ownerOrNil OptionsOrNil:(NSDictionary *)optionsOrNil {
     return [[UINib alloc] instantiateWithOwner:ownerOrNil options:optionsOrNil][0];
}

+ (FirstViewController *)firstViewOptionsOrNil:(NSDictionary *)optionsOrNil {
     return [[UINib alloc] instantiateWithOwner:nil options:optionsOrNil][0];
}


+ (UIView *)secondViewOptionsOrNil:(NSDictionary *)optionsOrNil {
     return [[UINib alloc] instantiateWithOwner:nil options:optionsOrNil][1];
}

+ (UIView *)secondViewOwnerOrNil:(id)ownerOrNil OptionsOrNil:(NSDictionary *)optionsOrNil {
     return [[UINib alloc] instantiateWithOwner:ownerOrNil options:optionsOrNil][1];
}

+ (UIView *)secondViewOwnerOrNil:(id)ownerOrNil {
     return [[UINib alloc] instantiateWithOwner:ownerOrNil options:nil][1];
}
@end


