//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

#import <UIKit/UIKit.h>

/// This `R.font` struct is generated, and contains static references to 5 fonts.

@interface UIFont (Font) 

/// `UIFont(name: "AveriaLibre-Bold", size: ...)`
+ (UIFont *)averiaLibreBoldSize:(CGFloat)size;


/// `UIFont(name: "AveriaLibre-BoldItalic", size: ...)`
+ (UIFont *)averiaLibreBoldItalicSize:(CGFloat)size;


/// `UIFont(name: "AveriaLibre-Light", size: ...)`
+ (UIFont *)averiaLibreLightSize:(CGFloat)size;


/// `UIFont(name: "AveriaLibre-Regular", size: ...)`
+ (UIFont *)averiaLibreRegularSize:(CGFloat)size;


/// `UIFont(name: "GoudyBookletter1911", size: ...)`
+ (UIFont *)goudyBookletter1911Size:(CGFloat)size;
@end


