//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

/// This `.string.generic` struct is generated, and contains static references to 13 localization keys.

@interface NSString (Generic) 

/// Value: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
+ (NSString *)loremipsum;


/// Value: Pre Alpha (| %#@first@ |)
+ (NSString *)correctAlphaFirst:(int)value1;


/// Value: Pre Beta (| %#@first@ x %#@second@ |)
+ (NSString *)correctBetaFirst:(int)value1 Second:(int)value2;


/// Value: Pre Delta (| %#@first@ |)
+ (NSString *)correctDeltaFirst:(int)value1 Second:(int)value2;


/// Value: Pre Epsilon (| %#@first@ |)
+ (NSString *)correctEpsilonFirst:(int)value1 Second:(int)value2;


/// Value: Pre Eta (| %@ - %#@second@ - %d|)
+ (NSString *)correctEtaValue1:(NSString *)value1 Second:(int)value2 Value3:(int)value3;


/// Value: Pre Gamma (| %2$#@second@ x %1$#@first@ |)
+ (NSString *)correctGammaFirst:(int)value1 Second:(int)value2;


/// Value: Pre Theta (| %#@first@ |)
+ (NSString *)correctThetaFirst:(int)value1 Second:(int)value2 Third:(int)value3;


/// Value: Pre Zeta (| %@ %2$#@second@ |)
+ (NSString *)correctZetaValue1:(NSString *)value1 Second:(int)value2;


/// Value: four  - %.2f
+ (NSString *)precision4Value1:(double)value1;


/// Value: one   - %012.2f
+ (NSString *)precision1Value1:(double)value1;


/// Value: three - %12.4f
+ (NSString *)precision3Value1:(double)value1;


/// Value: two   - %12.2f
+ (NSString *)precision2Value1:(double)value1;
@end



/// This `.string.localizable` struct is generated, and contains static references to 4 localization keys.

@interface NSString (Localizable) 

/// en translation: 2
/// 
/// Locales: en, es, ja
+ (NSString *)two;


/// en translation: One
/// 
/// Locales: en, es, ja
+ (NSString *)one;


/// en translation: There are %d lights!
/// 
/// Locales: en, es, ja
+ (NSString *)quoteValue1:(int)value1;


/// ja translation: Not translated in other languages, and there is no Base
/// 
/// Locales: ja
+ (NSString *)japaneseOnly;
@end



/// This `.string.settings` struct is generated, and contains static references to 10 localization keys.

@interface NSString (Settings) 

/// Base translation: %1$#@lu_completed_runs@
/// 
/// Locales: Base, nl
+ (NSString *)scopeLuOutOfLuRunsLu_completed_runs:(uint)value1 Lu_total_runs:(uint)value2;


/// Base translation: %1$d of %2$i files copied, %3$f.2%% completed.
/// 
/// Locales: Base, nl
+ (NSString *)copyProgressValue1:(int)value1 Value2:(int)value2 Value3:(double)value3;


/// Base translation: ABC "\DEF/" GHI Base
/// 
/// Locales: Base, nl
+ (NSString *)multilineKeyWeird;


/// Base translation: Base %#@first@
/// 
/// Locales: Base
+ (NSString *)incorrectInDutchFirst:(int)value1;


/// Base translation: Base language; Not translated
/// 
/// Locales: Base
+ (NSString *)notTranslated;


/// Base translation: Nothing
/// 
/// Locales: Base, nl
+ (NSString *)formatSpecifiers3Value1:(int)value1 Value2:(int)value2 Value3:(NSString *)value3;


/// Base translation: Settings
/// 
/// Locales: Base, nl
+ (NSString *)title;


/// Base translation: We need a couple things before you get started.
/// 
/// Locales: Base, nl
+ (NSString *)weNeedACoupleThingsBeforeYouGetStarted;


/// Base translation: number 1: %1$d
/// 
/// Locales: Base, nl
+ (NSString *)formatSpecifiers4Value1:(int)value1 Value2:(int)value2 Value3:(NSString *)value3;


/// Base translation: number 1: %d, number 2: %i, string 3: %@
/// 
/// Locales: Base, nl
+ (NSString *)formatSpecifiers1Value1:(int)value1 Value2:(int)value2 Value3:(NSString *)value3;
@end


